services:
  discord-bot-hoster:
    build: .
    container_name: proxmox-discord-bot-hoster
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - PORT=3000

